apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  namespace: bind9
  labels:
    app: bind9
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: internetsystemsconsortium/bind9:9.18
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: named-conf
              mountPath: /etc/bind/named.conf
              subPath: named.conf
            - name: zones
              mountPath: /var/lib/bind
      volumes:
        - name: named-conf
          configMap:
            name: bind9-config
            items:
              - key: named.conf
                path: named.conf
        - name: zones
          configMap:
            name: bind9-config
            items:
              - key: home.balzers.xyz.zone
                path: home.balzers.xyz.zone
