apiVersion: v1
kind: Service
metadata:
  name: bind9-service
spec:
  selector:
    app: bind9
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  type: LoadBalancer
  loadBalancerIP: 10.96.10.80