---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-shelter-li
  namespace: default
spec:
  secretName: local-shelter-li-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.shelter.li"
  dnsNames:
  - "local.shelter.li"
  - "*.local.shelter.li"