apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watchlistarr-data
  namespace: watchlistarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
