---
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /opt/appdata/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped