apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-data
  namespace: sonarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
