apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-data
  namespace: bazarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
