apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config-pvc
  labels:
    app: overseerr
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
