apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-data
  namespace: sabnzbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: longhorn
