---
- name: Reboot servers
  hosts: all
  become: yes
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible"
        pre_reboot_delay: 0
        post_reboot_delay: 30
        reboot_timeout: 600
        test_command: whoami
