---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  namespace: default
  labels:
    app: overseerr
spec:
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: overseerr
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
      - name: overseerr
        image: sctx/overseerr:latest
        ports:
        - containerPort: 5055
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: TZ
          value: "Europe/Zurich"
        - name: PORT
          value: "5055"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: overseerr-config-pvc
      restartPolicy: Always
