apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  namespace: default
  labels:
    app: overseerr
spec:
  selector:
    app: overseerr
  ports:
    - name: tcp
      port: 5055
      targetPort: 5055
