---
- name: Configure Zsh with plugins and set as default shell
  hosts: all
  become: true

  vars_prompt:
    - name: Username
      prompt: enter user id for whom you want to install zsh
      private: no

  tasks:
    - name: Check if Zsh is installed
      command: "rpm -q zsh"
      register: zsh_installed
      ignore_errors: yes

    - name: Install Zsh if not already installed
      dnf:
        name: zsh
        state: present
      when: zsh_installed.rc != 0

    - name: Copy Zsh configuration template
      template:
        src: ./templates/zshrc.j2
        dest: "/home/{{ Username }}/.zshrc"

    - name: Copy Zsh env configuration template
      template:
        src: ./templates/zshenv.j2
        dest: "/home/{{ Username }}/.zshenv"

    - name: Set Zsh as default shell for user {{ Username }}
      user:
        name: "{{ Username }}"
        shell: /bin/zsh
      become: true

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: /home/{{ Username }}/.zsh/zsh-autosuggestions
        clone: yes
      become: true
      become_user: "{{ Username }}"
